
          echo 'export BASH_ENV="$HOME/.bash_env"' >> ~/.zprofile

          # GitHub's default ~/.bash_profile contains:
          #
          #     POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-macos15
          #
          # WITHOUT ending with "\n". Add a "\n" manually, otherwise
          # the command is invalid.
          printf "\n%s\n" "set -euo pipefail" >> ~/.bash_profile

          brew install cmake boost hdf5 cgal vtk python3 octave

          # cython is keg-only, which means it was not symlinked into /opt/homebrew,
          # because this formula is mainly used internally by other formulae.
          # Users are advised to use `pip` to install cython.
          #
          # So Python will NOT be able to find cython from "site-package", nor
          # will the shell finds a cython executable from "bin"
          #
          # But then, `pip` can't be used directly due to PEP 668, which asks us
          # to install cython via the system's package manager, buh Howebrew does
          # not provide a fully-function package (unless you hack the symlinks
          # manually).
          #
          # So, the real solution is creating a virtualenv specifically for openEMS
          # usage.
          python3 -m venv $HOME/opt
          $HOME/opt/bin/pip3 install setuptools cython numpy h5py matplotlib

      - name: Checkout openEMS.git
        uses: actions/checkout@v4
        with:
          path: openEMS-Project
          submodules: recursive

          # checkout must be deep, not shallow.
          # We need tags for "git describe", otherwise build fails.
          fetch-depth: 0

      - name: Build and install openEMS
        run: |
          source ~/.zprofile
          cd $GITHUB_WORKSPACE/openEMS-Project

          # needed by Python modules
          source $HOME/opt/bin/activate  # activate venv

          if ./update_openEMS.sh ~/opt --python; then
            cat build_*.log
          else
            cat build_*.log
            exit 1
          fi

          echo "addpath('~/opt/share/openEMS/matlab')" >> ~/.octaverc
          echo "addpath('~/opt/share/CSXCAD/matlab')" >> ~/.octaverc

      - uses: actions/upload-artifact@v4
          with:
            name: macos-openems
            path: "~/opt/share/**/*

      - name: Smoketest Octave execution
        run: |
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/octave
          octave MSL_NotchFilter.m

      - name: Smoketest Python execution
        run: |
          cd $GITHUB_WORKSPACE/openEMS-Project/openEMS/.github/smoketests/python
          $HOME/opt/bin/python3 MSL_NotchFilter.py
